//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int empl_EmployeeID { get; set; }
        public string empl_Deleted { get; set; }
        public Nullable<int> empl_CreatedBy { get; set; }
        public Nullable<System.DateTime> empl_CreatedDate { get; set; }
        public Nullable<int> empl_UpdatedBy { get; set; }
        public Nullable<System.DateTime> empl_UpdatedDate { get; set; }
        public Nullable<int> empl_WorkflowID { get; set; }
        public Nullable<int> empl_WorkflowItemID { get; set; }
        public Nullable<int> empl_ZoneID { get; set; }
        public string empl_Code { get; set; }
        public string empl_Name { get; set; }
        public Nullable<int> empl_PositionID { get; set; }
        public Nullable<System.DateTime> empl_HiringDate { get; set; }
        public Nullable<System.DateTime> empl_ConfirmationDate { get; set; }
        public Nullable<System.DateTime> empl_ResignDate { get; set; }
        public Nullable<int> empl_DepartmentID { get; set; }
        public Nullable<int> empl_RootEmployeeID { get; set; }
        public string empl_WorkPermitNo { get; set; }
        public string empl_PayrollAccountNo { get; set; }
        public string empl_DOB { get; set; }
        public Nullable<int> empl_NationalityID { get; set; }
        public string empl_VisaNo { get; set; }
        public string empl_Address { get; set; }
        public string empl_Religion { get; set; }
        public string empl_Email { get; set; }
        public string empl_Phone { get; set; }
        public string empl_Phone2 { get; set; }
        public string empl_Spouse { get; set; }
        public string empl_Gender { get; set; }
        public string empl_POB { get; set; }
        public string empl_IDCard { get; set; }
        public string empl_Passport { get; set; }
        public string empl_NSSFNo { get; set; }
        public string empl_Level { get; set; }
        public Nullable<System.DateTime> empl_ProbationEnd { get; set; }
        public Nullable<decimal> empl_Salary { get; set; }
        public string empl_JD { get; set; }
        public Nullable<int> empl_Children { get; set; }
        public Nullable<System.DateTime> empl_ContractEndDate { get; set; }
        public string empl_ContractType { get; set; }
        public string empl_Token { get; set; }
        public string empl_Password { get; set; }
        public Nullable<decimal> empl_LeaveBallance { get; set; }
        public Nullable<decimal> empl_LeaveUsed { get; set; }
        public Nullable<decimal> empl_Leave { get; set; }
        public string empl_LeaveSchemeID { get; set; }
        public string empl_PayrollBenefitID { get; set; }
        public string empl_AdjustmentSchemeID { get; set; }
    }
}
