//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveSchemeItem
    {
        public int lvsi_LeaveSchemeItemID { get; set; }
        public string lvsi_Deleted { get; set; }
        public Nullable<int> lvsi_CreatedBy { get; set; }
        public Nullable<System.DateTime> lvsi_CreatedDate { get; set; }
        public Nullable<int> lvsi_UpdatedBy { get; set; }
        public Nullable<System.DateTime> lvsi_UpdatedDate { get; set; }
        public Nullable<int> lvsi_WorkflowID { get; set; }
        public Nullable<int> lvsi_WorkflowItemID { get; set; }
        public Nullable<int> lvsi_ZoneID { get; set; }
        public string lvsi_Name { get; set; }
        public Nullable<int> lvsi_PositionID { get; set; }
        public Nullable<int> lvsi_EmployeeID { get; set; }
        public Nullable<decimal> lvsi_Order { get; set; }
        public Nullable<int> lvsi_LeaveSchemeID { get; set; }
    }
}
