//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayrollBenefit
    {
        public int prbf_PayrollBenefitID { get; set; }
        public string prbf_Deleted { get; set; }
        public Nullable<int> prbf_CreatedBy { get; set; }
        public Nullable<System.DateTime> prbf_CreatedDate { get; set; }
        public Nullable<int> prbf_UpdatedBy { get; set; }
        public Nullable<System.DateTime> prbf_UpdatedDate { get; set; }
        public Nullable<int> prbf_WorkflowID { get; set; }
        public Nullable<int> prbf_WorkflowItemID { get; set; }
        public Nullable<int> prbf_ZoneID { get; set; }
        public string prbf_Type { get; set; }
        public Nullable<decimal> prbf_Amount { get; set; }
        public string prbf_Name { get; set; }
        public Nullable<int> prbf_EmployeeID { get; set; }
        public Nullable<System.DateTime> prbf_Date { get; set; }
        public Nullable<int> prbf_PayrollID { get; set; }
        public Nullable<int> prbf_PayrollPropID { get; set; }
        public Nullable<int> prbf_DepartmentID { get; set; }
        public Nullable<int> prbf_RecurrentID { get; set; }
        public string prbf_Status { get; set; }
    }
}
