//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayroll
    {
        public int payr_PayrollID { get; set; }
        public string payr_Deleted { get; set; }
        public Nullable<int> payr_CreatedBy { get; set; }
        public Nullable<System.DateTime> payr_CreatedDate { get; set; }
        public Nullable<int> payr_UpdatedBy { get; set; }
        public Nullable<System.DateTime> payr_UpdatedDate { get; set; }
        public Nullable<int> payr_WorkflowID { get; set; }
        public Nullable<int> payr_WorkflowItemID { get; set; }
        public Nullable<int> payr_ZoneID { get; set; }
        public Nullable<System.DateTime> payr_Date { get; set; }
        public string payr_Note { get; set; }
        public string payr_Name { get; set; }
        public Nullable<decimal> payr_NWD { get; set; }
        public Nullable<System.DateTime> payr_FrDate { get; set; }
        public Nullable<System.DateTime> payr_ToDate { get; set; }
        public Nullable<decimal> payr_ExRate { get; set; }
    }
}
