//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWorkHistory
    {
        public int wkhs_WorkHistoryID { get; set; }
        public string wkhs_Deleted { get; set; }
        public Nullable<int> wkhs_CreatedBy { get; set; }
        public Nullable<System.DateTime> wkhs_CreatedDate { get; set; }
        public Nullable<int> wkhs_UpdatedBy { get; set; }
        public Nullable<System.DateTime> wkhs_UpdatedDate { get; set; }
        public Nullable<int> wkhs_WorkflowID { get; set; }
        public Nullable<int> wkhs_WorkflowItemID { get; set; }
        public Nullable<int> wkhs_ZoneID { get; set; }
        public Nullable<System.DateTime> wkhs_FrDate { get; set; }
        public Nullable<System.DateTime> wkhs_ToDate { get; set; }
        public Nullable<int> wkhs_FrPositionID { get; set; }
        public Nullable<int> wkhs_ToPositionID { get; set; }
        public Nullable<decimal> wkhs_Salary { get; set; }
        public Nullable<int> wkhs_EmployeeID { get; set; }
        public string wkhs_Remarks { get; set; }
        public string wkhs_Status { get; set; }
        public Nullable<System.DateTime> wkhs_Resign { get; set; }
        public string FrPosition { get; set; }
        public string ToPosition { get; set; }
    }
}
